version: "3.3"

networks:
  postgreNet:
    name: postgreNet
    driver: bridge

services:
  api:
    build: .
    restart: on-failure
    container_name: ts-crud
    networks:
      - postgreNet
    image: ts-crud
    command: npm run start
    ports:
      - "5500:5500"
